### ISSUE TITLE
English Deepl not supported

### ISSUE THREAD

**Issue by brenthl88** [zyddnys/manga-image-translator#74] opened 2022-08-01 15:59 UTC
English deepl now split to American and British English
![Screenshot_20220801-085828_Firefox](https://user-images.githubusercontent.com/28693435/182190457-fd4000e9-ce57-4e03-9a2f-1e704feaf810.png)

**Comment by zyddnys** [comment] 2022-08-02 03:08
Can you provide the source image? Because deepl is working just fine for me.

**Comment by mspykerez** [comment] 2022-08-02 15:30
DeepL is also working for me, maybe he is from a banned country?

What is not been working for months is the text orientation that even when 'horizontal' is selected the translation always comes out as vertical.

**Comment by thatDudo** [comment] 2023-01-03 18:15
Closing as cannot be reproduced

**Closed by thatDudo** 2023-01-03 18:15 UTC
