### ISSUE TITLE
The image is not fully translated.

### ISSUE THREAD

**Issue by My12123** [zyddnys/manga-image-translator#208] opened 2023-02-02 13:00 UTC
![bboxes](https://user-images.githubusercontent.com/49092250/216331722-dc46024b-228c-4c92-b1df-573250576872.png)

**Comment by thatDudo** [comment] 2023-02-02 13:04
Duplicate of #204
Please post in the existing issue instead of opening new ones.

**Closed by thatDudo** 2023-02-02 13:04 UTC
