### ISSUE TITLE
[Feature Request]: OCR for English language

### ISSUE THREAD

**Issue by Grachy** [zyddnys/manga-image-translator#551] opened 2023-12-21 08:55 UTC
### What would your feature do?

Right now we have OCRs that only work with japanese, chinese, maybe korean, and are absolute disaster for english language, they ignore the easiest to recognice letters, we need an option to change OCR so you can translate from English too.

**Comment by zyddnys** [comment] 2023-12-21 19:48
can you share a failure example, the current OCR handle English pretty well

**Comment by zyddnys** [comment] 2023-12-21 20:11
can you try the latest version? i think the issue is caused by a mistake in textline merge, which was fixed in a7af9bbc66b59aa43a7700edc1522cdc30c0c651

**Comment by Grachy** [comment] 2023-12-22 05:02
will try it and tell how it goes.

**Comment by Grachy** [comment] 2023-12-25 05:24
I guess you didn't see my last msg, please update docker, so I can update everything at once.

**Closed** 2024-01-05 21:03 UTC
Labels: enhancement
